---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: clamav-server
  labels:
    app.kubernetes.io/name: clamav
    app.kubernetes.io/component: server

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

...
